- name: Create backup directory
  ansible.builtin.file:
    path: /mnt/backups
    state: directory
    mode: 700

- block:
    - name: Installation nfs-client package
      apt:
        name: nfs-client

    - name: Mount backup NFS partition
      when: backup_cron|bool == true
      ansible.posix.mount:
        src: "10.16.100.163:zpool-128310/{{backup_partition_name}}"
        path: /mnt/backups
        opts: _netdev,mountproto=tcp
        state: mounted
        fstype: nfs
        boot: yes

    - name: Add metabase backup cron"
      become: true
      cron:
        name: "backup metabase"
        minute: "20"
        hour: "0"
        job: "bash /opt/pilotage/tools/backup-metabase.sh >> /var/log/backup-metabase.log 2>&1"

    - name: Add storage backup cron"
      become: true
      cron:
        name: "backup OVH storage"
        minute: "30"
        hour: "0"
        job: "bash /opt/pilotage/tools/backup-storage.sh 2>&1"

  when: backup_partition_name is defined

- name: Ensure mounted directory has the same permission
  ansible.builtin.file:
    path: /mnt/backups
    state: directory
    mode: 700
